# Site settings
title: Olivia Ifrim
description: 'Intelligence is the ability to adapt to change.'
url: 'https://olivif.github.io/'
baseurl: '/'
# google_analytics: 'UA-97376068-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Olivia Ifrim'

social: 
  - twitter:
    name: twitter
    link: https://twitter.com/olly2204
  - github:
    name: github
    link: https://github.com/olivif
  - linkedin:
    name: linkedin
    link: https://www.linkedin.com/in/oliviaifrim/

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
